backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads
collections: 
  - label: "Homepage"
    name: "Homepage"
    files:
      - label: "Banner"
        name: "banner"
        format: "json"
        file: "/content/banner.json"
        fields:
          - label: "Top line"
            name: "topLine"
            widget: "string"
          - label: "Bottom line"
            name: "bottomLine"
            widget: "string"
          - label: "Button text"
            name: "buttonText"
            widget: "string"
          - label: "Slides"
            name: "slides"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image for Mobile", name: "mobileImage", widget: "image"}
      - label: "Get a quote form"
        name: "getaquote"
        format: "json"
        file: "/content/quote.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "string"
          - label: "Name placeholder"
            name: "namePlaceholder"
            widget: "string"
          - label: "Email placeholder"
            name: "emailPlaceholder"
            widget: "string"
          - label: "Company placeholder"
            name: "companyPlaceholder"
            widget: "string"
          - label: "Next button"
            name: "nextButton"
            widget: "string"
      - label: "How it works"
        name: "howitworks"
        format: "json"
        file: "/content/howitworks.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Timeframe", name: "timeframe", widget: "string"}
              - {label: "Image", name: "img", widget: "image"}
      - label: "About"
        name: "about"
        format: "json"
        file: "/content/about.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Paragraph 1"
            name: "paragraph1"
            widget: "string"
          - label: "Paragraph 2"
            name: "paragraph2"
            widget: "string"
          - label: "Checklist"
            name: "checklist"
            widget: "list"
          - label: "Button text"
            name: "buttonText"
            widget: "string"
      - label: "Services"
        name: "services"
        format: "json"
        file: "/content/services.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "string"
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Image", name: "img", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Identifier", name: "id", widget: "string"}
          - label: "Button text"
            name: "buttonText"
            widget: "string"
      - label: "Featured Project"
        name: "project"
        format: "json"
        file: "/content/services.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Project details"
            name: "projectDetails"
            widget: "list"
            fields:
              - {label: "Image", name: "img", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Additional category", name: "additionalCategory", widget: "string"}
          - label: "Button text"
            name: "buttonText"
            widget: "string"
      - label: "Why steel framing?"
        name: "iconbox.json"
        format: "json"
        file: "/content/iconbox.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Selling Points"
            name: "items"
            widget: "list"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
          - label: "Button text"
            name: "buttonText"
            widget: "string"
      - label: "Footer"
        name: "footer"
        format: "json"
        file: "/content/footer.json"
        fields:
          - label: "Rights"
            name: "rights"
            widget: "string"
          - label: "Logo"
            name: "logo"
            widget: "string"
          - label: "Header 1"
            name: "site"
            widget: "string"
          - label: "Header 2"
            name: "contact"
            widget: "string"
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link to", name: "link", widget: "string"}
          - label: "Telephone"
            name: "tel"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Address"
            name: "address"
            widget: "string"
  - label: "Contact"
    name: "Contact"
    files:
      - label: "Contact"
        name: "contact"
        format: "json"
        file: "/content/contact.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "string"
          - label: "Name placeholder"
            name: "namePlaceholder"
            widget: "string"
          - label: "Phone placeholder"
            name: "phonePlaceholder"
            widget: "string"
          - label: "Email placeholder"
            name: "emailPlaceholder"
            widget: "string"
          - label: "Subject placeholder"
            name: "subjectPlaceholder"
            widget: "string"
          - label: "Message placeholder"
            name: "messagePlaceholder"
            widget: "string"
          - label: "Send button"
            name: "sendButtonText"
            widget: "string"
          - label: "Information header"
            name: "information"
            widget: "string"
          - label: "Address"
            name: "address"
            widget: "string"
          - label: "Call to action"
            name: "callUs"
            widget: "string"
          - label: "Telephone"
            name: "tel"
            widget: "string"
          - label: "Email call to action"
            name: "emailus"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Message sent successfully"
            name: "success"
            widget: "string"
          - label: "Error sending message"
            name: "error"
            widget: "string"
  - label: "Projects"
    name: "Projects"
    files:
      - label: "Projects"
        name: "projects"
        format: "json"
        file: "/content/projects.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Top image", name: "img", widget: "image"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Type of project", name: "type", widget: "string"}
              - label: "Project images"
                name: "otherImages"
                widget: "object"
                fields:
                  - label: "Images"
                    name: "images"
                    widget: "list"
                    field:
                      - {label: "Project image", name: "img", widget: "image"}
  - label: "Services"
    name: "Services"
    files:
      - label: "Services"
        name: "services"
        format: "json"
        file: "/content/services.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "string"
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Image", name: "img", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
  - label: "Why Steel"
    name: "whysteel"
    files:
      - label: "Why Steel"
        name: "whysteel"
        format: "json"
        file: "/content/whysteel.json"
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "About"
            name: "about"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "string"
          - label: "Image"
            name: "img"
            widget: "image"
          - label: "Selling points"
            name: "points"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "list"}
  - label: "Quote"
    name: "quoteform"
    files:
      - label: "Quote"
        name: "quote"
        format: "json"
        file: "/content/quote.json"
        fields:
          - label: "Start your project"
            name: "partnerTitle"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "string"
          - label: "Name placeholder"
            name: "namePlaceholder"
            widget: "string"
          - label: "Missing name"
            name: "nameMissing"
            widget: "string"
          - label: "Email placeholder"
            name: "emailPlaceholder"
            widget: "string"
          - label: "Email missing"
            name: "emailMissing"
            widget: "string"
          - label: "Company placeholder"
            name: "companyPlaceholder"
            widget: "string"
          - label: "Next button"
            name: "nextButton"
            widget: "string"
          - label: "Page"
            name: "page"
            widget: "string"
          - label: "Next page"
            name: "next"
            widget: "string"
          - label: "Back"
            name: "back"
            widget: "string"
          - label: "Yellow tick"
            name: "yellowTick"
            widget: "image"
          - label: "Type of project title"
            name: "typeOfProjectTitle"
            widget: "string"
          - label: "Type of project"
            name: "typeOfProject"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Image", name: "img", widget: "image"}
          - label: "Tick"
            name: "tick"
            widget: "image"
          - label: "Residential project"
            name: "residentialProject"
            widget: "string"
          - label: "Commercial project"
            name: "commercialProject"
            widget: "string"
          - label: "Profession"
            name: "profession"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Professions", name: "professions", widget: "list"}
          - label: "Project type"
            name: "projectType"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Type", name: "type", widget: "list"}
          - label: "Detail for residential project"
            name: "detail"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Detail", name: "detail", widget: "list"}
          - label: "Detail for commercial project"
            name: "commercialDetail"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Detail", name: "detail", widget: "list"}
          - label: "DA approval"
            name: "DAApproval"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Options", name: "approval", widget: "list"}
          - label: "No DA approval"
            name: "noDAApproval"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Reasons", name: "reasons", widget: "list"}
          - label: "Architectural plan"
            name: "architecturalPlan"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Options", name: "plans", widget: "list"}
              - {label: "Upload", name: "upload", widget: "string"}
              - {label: "Upload button", name: uploadButton, widget: "string"}
          - label: "Engineering plan"
            name: "engineeringPlan"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Options", name: "plans", widget: "list"}
              - {label: "Upload", name: "upload", widget: "string"}
              - {label: "Upload button", name: uploadButton, widget: "string"}
          - label: "Structural plan"
            name: "structuralPlan"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Options", name: "plans", widget: "list"}
          - label: "No architectural plan"
            name: "sorry"
            widget: "string"
          - label: "Return to homepage"
            name: "returnHome"
            widget: "string"
          - label: "Quote for"
            name: "quoteFor"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Type", name: "type", widget: "list"}
          - label: "Start project"
            name: "startProject"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Timeframe", name: "timeframe", widget: "list"}
          - label: "Message"
            name: "message"
            widget: "string"
          - label: "Submit button"
            name: "submitButton"
            widget: "string"
          - label: "Thank you title"
            name: "thankYou"
            widget: "string"
          - label: "Thank you message"
            name: "thankYouMessage"
            widget: "string"
          